# Generated by Django 3.2.3 on 2021-06-23 13:16

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percent', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(default=checkout.models.Coupon.next_day)),
            ],
        ),
    ]
