# Generated by Django 3.2.3 on 2021-06-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_coupons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
    ]
