# Generated by Django 3.2.3 on 2021-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_used_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='used_coupon',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
