# Generated by Django 3.2.3 on 2021-06-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210608_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='name',
            new_name='title',
        ),
    ]
